---
- hosts: frontends

  tasks:
  - command: echo {{ item }}
    loop: [ 1, 2, 3, 4, 5, 6 ]
    when: item > 3
  - name: grant permission for each user in multiple data sources
    postgresql_user:
      name: "{{ item[0] }}"
      priv: "ALL/{{ item[1] }}:ALL"
      password: "admin"
      db: postgres
    loop: "{{ ['daniel', 'justine'] |product(['customerdb', 'preferencedb', 'referencedb'])|list }}"
    remote_user: postgres
  - shell: "echo {{ item }}"
    loop:
    - "here"
    - "there"
    register: echo
