---
- hosts: all

  tasks:
  - yum:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    tags:
    - installation
  - template:
      src: templates/src.j2
      dest: /etc/nginx.confg
    tags:
    - customization
