---
- hosts: appservers
  name: rolling updates task
  serial:
  - "10%"
  - "30%"
  - "100%"
  gather_facts: False

  tasks:
  - name: task one
    command: date
  - name: task two
    command: date
