---
- hosts: frontends
  become: true

  handlers:
  - name: Start apache web server
    service:
      name: httpd
      state: started
    listen: "start all services"

  tasks:
  - name: start all services
    debug:
    changed_when: true
    notify: "start all services"
